### ISSUE TITLE
Search does not work as expected

### ISSUE THREAD

**Issue by patrickelectric** [Williangalvani/TlogViewer#135]
I was searching for RCOUT
![image](https://user-images.githubusercontent.com/1215497/76988768-057c6900-6924-11ea-8f2d-255c69d4ffa2.png)
![image](https://user-images.githubusercontent.com/1215497/76988809-1a58fc80-6924-11ea-852e-39569687f1f8.png)

**Comment by Williangalvani** [comment]
search seems to be still very messed up, nice catch
