### ISSUE TITLE
Interface start an infinity load after selecting some values 

### ISSUE THREAD

**Issue by patrickelectric** [Williangalvani/TlogViewer#136]
After selecting some items, the starts an infinity load to a different time-space reference
![image](https://user-images.githubusercontent.com/1215497/76989212-c26ec580-6924-11ea-97a5-fe9962867111.png)

**Comment by Williangalvani** [comment]
happens in this log when trying to plot XKF3.IYAW

[00000104.zip](https://github.com/Williangalvani/TlogViewer/files/4350506/00000104.zip)
